### ISSUE TITLE
gr-igate trims whitespace from end of APRS packets

### ISSUE THREAD

**Issue by hessu** [pengi/gr-igate#3]
Hi,

gr-igate trims whitespace from end of igated packets using the rstrip() string method:

https://github.com/pengi/gr-igate/blob/master/python/aprs_decode_frame.py#L113

APRS packet data should not be modified in any way before passing on to the APRS-IS. Space character at the end of the packet is used (amongst other things) as the Mic-E type code for Yaesu VX-8 (http://www.aprs.org/aprs12/mic-e-types.txt). When gr-igate removes that space, and other software without that bug does not remove it, we'll end up with two different copies of the same packet on the APRS network. For the long story:

https://github.com/hessu/aprsc/blob/master/doc/IGATE-HINTS.md#packets-modified-by-igates

Overall, I am really happy to see gr-igate; since it's a pure-python igate solution built straight on top of gnuradio, it is in a good position to act as a simple igate that does not corrupt packets. Since gr-igate gets to process raw AX.25 frames, it should be much simpler and easier to get it working right, when compared to the older multimon-based approach which relies on the user interface of multimon which already has corrupted the packets in various ways.

Thanks!

**Comment by pengi** [comment]
Oh, thanks!

It's not "pure" python, since there is a simple clock recovery routine added in c++, since it's in the line of raw samples. So the c++ toolchain is needed too, unfortunately.

I'll try to fix it as soon as possible. I want to add some unit tests for it too. So it might take a couple of days though.

**Comment by hessu** [comment]
Excellent, thank you very much! I'm looking forward to running this somewhere soon.

While you are at it, please add a little unit test to see that all 0x00...0xFF byte values go through when placed in the info/data part, with the exception of CR/LF which terminate the packet. With python it might be easy to get in trouble with unicode string encodings.

Also, if the original packet has multiple lines, only send the first line (stop at first CR or LF seen, although CR is the standard on AX.25), since APRS-IS can only deal with single-line packets.

**Comment by pengi** [comment]
Should be fixed, and test is available.

I don't have access to any CI environment that can run gnuradio, so I have to trust my laptop.

However, if you could have a look at the diff in the related commit, it would be great with some extra eyes

The commit fixing the issue is: 90f3f9e8a26713004a476b014081f4e17bea5bd2

**Comment by hessu** [comment]
Excellent, looks good, especially with having the unit tests in place! That's unfortunately pretty rare in the APRS world, to have actual testing automation.
